iMariaDB only. Using pre-installed mariadb only.

diff --git a/my b/my
--- a/my
+++ b/my
@@ -1,24 +1,12 @@
 #!/bin/bash
 
-### Urr...Readme?
-# Set the following in your bash profile or preferably ~/.mim
-# MIMHOME, the directory where configs, datadir, and templates will reside
-# MIMBINARIES, the directory where all your mysql/mariadb .tar.gz files are
-# MIMROOTPASS, set a desired root password.
-# DBSHELLNAME, optional prompt name default is 'SQL'
-# MIMSECURE=0, 1=Set the root user password to $MIMROOTPASS and delete blank users. 0=Leave database defaults.
-# DEFAULTDATABASE, set the default database for connecting to a server
 
-### Stop reading now.
-
+export MIMHOME=${HOME}/.mim
+export BASEDIR=$(dirname $(which mysqld))
 
 
 firstrun()
 {
-    if [[ -z $MIMHOME ]]
-    then
-	echo "MIMHOME has not been declared"
-    else
 	if [[ ! -d $MIMHOME ]]
 	then
 	    mkdir -p $MIMHOME
@@ -34,7 +22,6 @@ firstrun()
 		mkdir $MIMHOME/$dir
 	    fi
 	done
-    fi
 }
 
 getvar()
@@ -66,8 +53,7 @@ setup\trun through first run setup
 status\tshow installed server status
 aliases\tshow aliases for all instances
 \nInstance Management:\n--
-build\t[server name]\t[port]\tcreate a server config
-install\t[server name]\tinstall a server from config
+create\t[server name]\t[port]\tcreate and install a server from config
 drop\t[server name]\tdrops instance datadir AND config!
 start\t[server name]
 stop\t[server name]
@@ -83,36 +69,12 @@ help\tthis message
 exit 0
 }
 
-install()
-{
-    BASEDIR=$(getvar basedir $CONFIGFILE)
-    DATADIR=$(getvar datadir $CONFIGFILE)
-    TMPDIR=$(getvar tmpdir $CONFIGFILE)
-    if [[ -d $DATADIR ]]
-    then
-	echo "$DATADIR already exists, aborting"
-	exit 1
-    else
-	mkdir -p $TMPDIR
-	if [[ -d $TMPDIR ]]
-	then
-	    cd $BASEDIR
-	    ./scripts/mysql_install_db --defaults-file=$CONFIGFILE 2>&1
-	    exit 0
-	else
-	    echo "Creating $TMPDIR failed, aborting"
-	    exit 1
-	fi
-    fi
-}
-
 start()
 {
     echo '' > /tmp/$SERVERNAME.log
     SERVERPORT=$(getvar port $CONFIGFILE)
-    BASEDIR=$(getvar basedir $CONFIGFILE)
     echo "Starting $SERVERNAME on $SERVERPORT"
-    $BASEDIR/bin/mysqld_safe --defaults-file=$CONFIGFILE --ledir=$BASEDIR/bin $CLUSTERCMD > /tmp/$SERVERNAME.log 2>&1 &
+    mysqld_safe --defaults-file=$CONFIGFILE $CLUSTERCMD > /tmp/$SERVERNAME.log 2>&1 &
     sleep 2
     cat /tmp/$SERVERNAME.log
 }
@@ -121,9 +83,8 @@ stop()
 {
     SERVERPORT=$(getvar port $CONFIGFILE)
     SERVERSOCK=$(getvar socket $CONFIGFILE)
-    BASEDIR=$(getvar basedir $CONFIGFILE)
     echo "Stopping $SERVERNAME on $SERVERPORT"
-    $BASEDIR/bin/mysqladmin -uroot --socket=$SERVERSOCK -P $SERVERPORT shutdown
+    mysqladmin -uroot --socket=$SERVERSOCK -P $SERVERPORT shutdown
 }
 
 status()
@@ -171,11 +132,7 @@ aliases()
 	    SERVERNAME=$(basename $conf .cnf)
 	    SERVERPORT=$(getvar port $conf)
 	    SERVERSOCK=$(getvar socket $conf)
-	    if [[ -z $DBSHELLNAME ]]
-	    then
-		DBSHELLNAME="SQL"
-	    fi
-	    PROMPTOPT="\"${DBSHELLNAME} [\d] > \""
+	    PROMPTOPT="\"${SERVERNAME}:${SERVERPORT} [\d] > \""
 	    printf "alias ${SERVERNAME}='mysql -P${SERVERPORT} --socket=${SERVERSOCK} --prompt=${PROMPTOPT}'\n"
 	done
     fi
@@ -188,19 +145,17 @@ do_all()
 	echo "No configs found in $CONFDIR, run 'my build' first"
 	exit 0
     else
-	declare -a mybins  
 	for conf in $CONFDIR/*.cnf
 	do
 	    SERVERNAME=$(basename $conf .cnf)
 	    SERVERPORT=$(getvar port $conf)
 	    SERVERSOCK=$(getvar socket $conf)
-	    BASEDIR=$(getvar basedir $conf)
-	    MYSQLALIVE=$($BASEDIR/bin/mysqladmin -uroot --socket=$SERVERSOCK ping 2>/dev/null | wc -l)
+	    MYSQLALIVE=$(mysqladmin -uroot --socket=$SERVERSOCK ping 2>/dev/null | wc -l)
 
 	    if [[ $MYSQLALIVE -ne 0 ]]
 	    then
 		printf "${SERVERNAME}\n--\n"
-		$BASEDIR/bin/mysql -uroot --socket=$SERVERSOCK -NBe "${DO};"
+		mysql -uroot --socket=$SERVERSOCK -NBe "${DO};"
 	    fi
 	done
     fi
@@ -239,82 +194,20 @@ drop()
 
 }
 
-selectversion()
+selectextraconfig()
 {
-    select MYVER in $MIMBINARIES/*.tar.gz;
+    select EXTRA_CONFIG in $EXTRA_CONFIGS_DIR/*;
     do
-	BASEDIR=${MIMBINARIES}/$(basename $MYVER .tar.gz)
-	if [[ ! -d $BASEDIR ]]
-	then
-	    echo "$BASEDIR not found, extracting $MYVER"
-	    tar -xf $MYVER -C ${MIMBINARIES}
-	fi
-	# Check the extracted directory is the same as the basename $MYVER
-
-	if [[ ! -d $BASEDIR ]]
-	then
-	    printf "\nWARNING:\n--\n${MYVER}\ndoes not match:\n${BASEDIR}\nWhich is the correct directory?\n"
-	    select CORRECTDIR in $(ls -d $MIMBINARIES/*/); do
-		if [[ -d $CORRECTDIR ]]
-		then
-		    mv $CORRECTDIR $BASEDIR
-		fi
-		break
-	    done
-	fi
-
-	echo "Using $MYVER"
+	export EXTRA_CONFIG=$MYEXTRA_CONFIG
+	echo "Using $EXTRA_CONFIG"
 	break
     done
 }
 
-selecttemplate()
+create()
 {
-    select MYTEMPLATE in $TEMPLATEDIR/*;
-    do
-	export CONFIGTEMPLATE=$MYTEMPLATE
-	echo "Using $CONFIGTEMPLATE"
-	break
-    done
-}
+	selectextraconfig
 
-selectclient()
-{
-    if [[ -z $SERVERNAME ]]
-    then
-	echo "Missing parameter"
-	showhelp
-	exit 0
-    else
-	BASEDIR=$(getvar basedir $CONFIGFILE)
-	printf "export PATH=${BASEDIR}/bin:\$PATH\n"
-	printf "export LD_LIBRARY_PATH=${BASEDIR}/lib\n"
-    fi
-}
-
-build()
-{
-    if [[ -z $ID ]]
-    then
-	echo "server-id was not assigned, using date. Is the date command in your PATH?"
-	exit 0
-    fi
-
-    if [[ ! -d $MIMBINARIES ]]
-    then
-	echo "$MIMBINARIES does not exist, aborting"
-	exit 0
-    else
-	selecttemplate
-	selectversion
-    fi
-
-    if [[ -z $BASEDIR && -z $CONFIGTEMPLATE ]]
-    then
-	echo "Need a Version and Config Template, aborting"
-	exit 1
-
-    else
 	if [[ -e $CONFDIR/${SERVERNAME}.cnf ]]
 	then
 	    echo "${SERVERNAME}.cnf already exists! Overwrite?"
@@ -326,65 +219,68 @@ build()
 	done
     else touch $CONFDIR/${SERVERNAME}.cnf
     fi
+    if [[ -z ${EXTRA_CONFIG} ]]
+	then
+		INCLUDE_LINE=""
+	else
+		INCLUDE_LINE="!include ${EXTRA_CONFIG}"
+	fi
 
     echo "Adding new detaults to $CONFDIR/${SERVERNAME}.cnf"
     if [[ -e $CONFDIR/${SERVERNAME}.cnf ]]
     then
 	echo -e "
-	[mysqld]
-	user				= $USER
-	server-id		   = $ID
-	basedir			 = $BASEDIR
-	tmpdir			  = $TMPDIR
-	port				= $PORT
-	datadir			 = $DATADIR
-	socket			  = $DATADIR/mysql.sock
-	pid_file			= $DATADIR/mysql.pid
-	log-bin			 = $DATADIR/mysql-log-bin
-	log-bin-index	   = $DATADIR/mysql-log-bin.index
-	log_error		   = $DATADIR/error.log
-	slow_query_log_file = $DATADIR/slow.log
+[mysqld]
+user = $USER
+server-id = $ID
+basedir = $BASEDIR
+tmpdir = $TMPDIR
+port = $PORT
+datadir = $DATADIR
+socket = $DATADIR/mysql.sock
+pid_file = $DATADIR/mysql.pid
+log-bin = $DATADIR/binlog
+log-bin-index = $DATADIR/binlog.index
+log_error = $DATADIR/error.log
+slow_query_log_file = $DATADIR/slow.log
 
-	!include $CONFIGTEMPLATE" > $CONFDIR/${SERVERNAME}.cnf
+${INCLUDE_LINE}" > $CONFDIR/${SERVERNAME}.cnf
 	exit 0
     else
 	echo "$CONFDIR/${SERVERNAME}.cnf not found? Exiting."
 	exit 1
     fi
 
-fi
+    DATADIR=$(getvar datadir $CONFIGFILE)
+    TMPDIR=$(getvar tmpdir $CONFIGFILE)
+    if [[ -d $DATADIR ]]
+    then
+	echo "$DATADIR already exists, aborting"
+	exit 1
+    else
+	mkdir -p $TMPDIR
+	if [[ -d $TMPDIR ]]
+	then
+	    mysql_install_db --defaults-file=$CONFIGFILE 2>&1
+	    exit 0
+	else
+	    echo "Creating $TMPDIR failed, aborting"
+	    exit 1
+	fi
+    fi
+
+
 }
 
 
 ### MAIN ###
-declare -a req_dir=(configs templates data)
+declare -a req_dir=(configs extra_configs data)
 ERRORCOUNTER=0
-MIMCONFIG=$HOME/.mim
-
-if [[ -e $MIMCONFIG ]]
-then
-    source $MIMCONFIG
-fi
 
 if [[ -z $MIMHOME ]]
 then
     echo "MIMHOME not defined"
     let ERRORCOUNTER+=1
-fi
-
-if [[ -z $MIMBINARIES ]]
-then
-    echo "MIMHOME not defined"
-    let ERRORCOUNTER+=1
-elif [[ ! -d $MIMBINARIES ]]
-then
-    echo "MIMBINARIES defined, but directory does not exist"
-    let ERRORCOUNTER+=1
-fi
-
-if [[ -z $MIMROOTPASS ]]
-then
-    MIMROOTPASS=""
 fi
 
 if [[ $ERRORCOUNTER -ne 0 ]]
@@ -393,7 +289,7 @@ then
     exit 0
 else
     CONFDIR=$MIMHOME/configs
-    TEMPLATEDIR=$MIMHOME/templates
+    EXTRA_CONFIGS_DIR=$MIMHOME/extra_configs
     if [[ ! -d $MIMHOME ]]
     then
 	echo "$MIMHOME does not exist, run setup?"
@@ -402,8 +298,7 @@ else
 		Yes ) firstrun
 		    break
 		    ;;
-		No )  echo "please create $MIMHOME manually"
-		    exit 1
+		No ) exit 0
 		    ;;
 	    esac
 	done
@@ -448,12 +343,6 @@ else
     SERVERNAME=$2
 fi
 
-if [[ $1 == "install" && $# -eq 2 ]]
-then
-    install
-    exit 0
-fi
-
 if [[ $1 == "start" ]]
 then
     if [[ -z $2 ]]
@@ -488,12 +377,6 @@ fi
 if [[ $1 == "stop" && $# -eq 2 ]]
 then
     stop
-    exit 0
-fi
-
-if [[ $1 == "client" && $# -eq 2 ]]
-then
-    selectclient
     exit 0
 fi
 
@@ -572,7 +455,7 @@ then
     fi
 fi
 
-if [[ $1 == "build" && $# -eq 3 ]]
+if [[ $1 == "create" && $# -eq 3 ]]
 then
     if [[ -z $2 ]]
     then
@@ -590,7 +473,9 @@ then
     ID=$(date '+%s')
     DATADIR=$MIMHOME/data/$SERVERNAME
     TMPDIR=$DATADIR/tmp
-    build
+    CONFIGFILE=$CONFDIR/$2.cnf
+    SERVERNAME=$2
+    create
     exit 0
 else
     echo "Incorrect Parameters"
